### ISSUE TITLE
lib folder conflict

### ISSUE THREAD

**Issue by gsgoldma** [ljleb/prompt-fusion-extension#24]
i believe there's a module conflict from multiple extensions using lib folder

this was just resolved with unprompted/depthmap by unprompted changing lib to lib_unprompted,

as I just got an error with depthmap script again, I bet it's the .py files in the lib folder, being loaded before depthmap, then depthmap starts looking in prompt fusion lib folder instead of its own. 

something like that anyway, im not an expert. but that is what was described in the previous scenario

**Comment by ljleb** [comment]
Sure, I'll rename the folder to `lib_prompt_fusion`. Wasn't aware of it, thanks for the help.

**Comment by ljleb** [comment]
Should be fixed now. Don't forget to restart the webui completely as only the script files under `/scripts` are reloaded on ui reload.
