### ISSUE TITLE
Prompt variable definitions don't stop at the first newline character

### ISSUE THREAD

**Issue by John-WL** [ljleb/prompt-fusion-extension#29]
For instance, if I write the following prompt, then the rest of the prompt is used as the variable definition scope, and not just what's defined on the line:
```
$label = prompt

this is my $label
```

It works if I add parentheses around it, though (but they are still parsed as weights):
```
$label = (prompt:1)

this is my $label
```

**Comment by ljleb** [comment]
I'll do it along with #16
