### ISSUE TITLE
Mention similarity to "prompt blending" technique

### ISSUE THREAD

**Issue by Hellisotherpeople** [ljleb/prompt-fusion-extension#34]
This is an AWESOME project and AWESOME idea, and I'm going to talk about it on linkedin. 

I noticed that this is similar to the "prompt blending" custom script. Might be cool to give them a shoutout! 

https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Custom-Scripts#prompt-blending

**Comment by ljleb** [comment]
Thank you, glad you like the idea.

The Prompt Blending extension is pretty useful! We were talking about implementing something like this in fusion IRL 2 days ago but it seems that won't be necessary ;)

I'll add a mention to Prompt Blending in the readme when I'm in front of my pc. Thanks for bringing it up!

**Comment by John-WL** [comment]
I added a reference to the script on the readme.
