### ISSUE TITLE
[Feature Request] Enable/disable toggle

### ISSUE THREAD

**Issue by catboxanon** [ljleb/prompt-fusion-extension#38]
Would it be possible to have an enable/disable toggle in settings or similar? Most extensions have a separate toggle for this as doing it from the extensions tab requires the whole webui to be restarted. It may be useful as well for troubleshooting incase something were to break down the line, and you can do a quick check if this extension happens to be the cause or not.

**Comment by ljleb** [comment]
As it's a relatively narrow feature I'll look up how to move the checkbox to the settings tab.
