### ISSUE TITLE
Add alternative delimeter for X/Y plot script

### ISSUE THREAD

**Issue by freezerain** [ljleb/prompt-fusion-extension#52]
Problem: when using X/Y plot script comas parsed as plot delimeter

Suggestion:
-make an option to use alternative delimeter, for examle "||" (can conflict with infinite tables), "//", "..." or anythin that user specifies in settings
-rework prompt_parser.py to hijack promp before X/Y script 

Example of "[girl:dragon:0.1,0.5], " Prompt S/R 

![tmpxzpgmdhs](https://github.com/ljleb/prompt-fusion-extension/assets/35431136/500f4ab0-edd4-4123-a088-cec873892a8d)

**Comment by freezerain** [comment]
it shoud be [girl :  dragon] but github decided to insert emoji in my message, while it is cute yet confusing

**Comment by ljleb** [comment]
X/Y/Z values are CSV entries. To put comas, you can put an entry in quotes like this:

```
"[ girl : dragon : 0.1 , 0.5 ]"," "
```

**Comment by freezerain** [comment]
oh thank you
