### ISSUE TITLE
ComfyUI

### ISSUE THREAD

**Issue by Arthur-McArthur** [ljleb/prompt-fusion-extension#55]
This might be a long shot be is there any way to achieve this functionality in ComfyUI? Or plans to port your extension to it?

It is my most used extension by far and dramatically increases the capabilities of SD. It would be great to have it in ComfyUI

**Comment by ljleb** [comment]
At the moment I think I would need a custom kdiffusion node for this, which is not ideal.

We are working on inserting comfyui into multiple sections of the webui for increased generation control. For example, you will be able to run a workflow at each denoising step of the webui to determine how denoising should happen. It is still in its infancy state yet, but you can keep an eye on it as we increase the integration:
https://github.com/ModelSurge/sd-webui-comfyui/

Once we get to a more mature and stable state, I'll be looking to add prompt fusion nodes and a default workflow.

**Comment by ljleb** [comment]
There seems to be comfyui nodes that achieve this now. I have not successfully installed them but also haven't spent too much time on it: https://github.com/asagi4/comfyui-prompt-control
