### ISSUE TITLE
Doesn't work in SD.Next (automatic1111 fork)...

### ISSUE THREAD

**Issue by Alverik** [ljleb/prompt-fusion-extension#58]
Hi, I was trying this on Vladmandic's SD.NEXT (a fork of Automatic1111), but the extension doesn't work in it. Any chance we can get a fix or fork that works with SD.Next?... It would be greatly appreciated.

**Comment by ljleb** [comment]
it seems to work on the latest version. Please fill in more details if there is still a problem.
