### ISSUE TITLE
Fractional step values for 1.6.0 hires prompt editing does not work

### ISSUE THREAD

**Issue by ljleb** [ljleb/prompt-fusion-extension#62]
Fractional step values for hires prompt editing, i.e. `[wolf : dog : 1.5]` are broken by this extension. It does not prevent generation, but the values are cast to int and taken as step numbers, which is wrong.

**Comment by SirVeggie** [comment]
Any ETA on this fix?

**Comment by ljleb** [comment]
5 minutes.

**Comment by SirVeggie** [comment]
Amazing

**Comment by SirVeggie** [comment]
Seems like it did not quite work. Now the resulting image is quite close to the expected result but there is still something wrong, [::1.1] and [::1.9] produce an almost identical image, whereas the difference is somewhat bigger when the extension is disabled.

**Comment by ljleb** [comment]
This is because in the background the extension converts float steps to step indices no matter what. Will push a fix shortly.

**Comment by ljleb** [comment]
I did test the feature a little bit. Except for a few cases I may have missed, the new syntax should work. You should also be able to use the previous syntax by checking the "use old prompt editing timelies" checkbox in the compatibility options.

**Comment by SirVeggie** [comment]
After using it for quite some time, I do think it is working well now.
