### ISSUE TITLE
intel alchemist gpus lack fp64 support

### ISSUE THREAD

**Issue by NoAvailableAlias** [ljleb/prompt-fusion-extension#78]
Image generation using the directml fork of A1111 is failing to generate when using an Intel a770 gpu due to its lack of fp64 support.

Not sure which specific commit or file the culprit change is located but it's related to introducing either fp64 instructions or fp64 types.

Several months ago, (the last time I had tried SD with intel arc), this extension worked perfectly.

**Comment by ljleb** [comment]
Thanks for letting me know, I wasn't aware of the partial support for fp64 in some scenarios. It's from [one of the latest commits](https://github.com/ljleb/prompt-fusion-extension/commit/8692c63aa4b208004672af6ea04138965df3f37e#diff-310712dd9ac6600913584086cb2d6e8e5610edd3941e55ffe45a11ecb7dec968R42) where I noticed that interpolation in diff space for slerp introduced a large precision error. fp64 basically fixed this but IIRC fp32 should work equally well. Let me test it and then I'll push if it's good enough.

**Comment by ljleb** [comment]
Should be fixed now, please let me know if there is still a problem after updating the extension to the latest version.

**Comment by NoAvailableAlias** [comment]
Confirmed, it is back to working for intel arc.
Hopefully a suitable workaround is found for that mentioned precision issue, sucks that "modern" hardware is like this
